<?xml version="1.0"?>

<!-- A simple model of the rc-car for rviz -->
<!-- urdf-viz for quick viewing-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rc-car">



  <xacro:property name="wheelbase" value="0.222" />
  <xacro:property name="width" value="0.100" />
  <xacro:property name="height" value="0.110" />
  <xacro:property name="ground_offset" value="0.070" />
  <xacro:property name="wheel_offset" value="0.025" />
  <xacro:property name="wheel_radius" value="0.06" />
  <xacro:property name="wheel_length" value="0.055" />
  <xacro:property name="laser_distance_from_base_link" value="0.275" />
  <xacro:property name="laser_height" value="0.05" />
  <xacro:property name="laser_radius" value="0.026" />
  <xacro:property name="imu_distance_from_base_link" value="0.1" />
  <xacro:property name="imu_height" value="0.01" />
  <xacro:property name="imu_radius" value="0.025" />
  <xacro:property name="imu_distance_from_base_link" value="0.0" />
  <xacro:property name="imu_height" value="0.01" />
  <xacro:property name="imu_radius" value="0.025" />

  <material name="black">
    <color rgba="0.2 0.2 0.2 1"/>
  </material>

  <material name="blue">
    <color rgba="0.3 0.57 1 1"/>
  </material>

  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>

  ### base link
  <link name="base_link">
    <visual>
      <origin xyz="${wheelbase/2} 0 ${ground_offset+height/2}"/>
      <geometry>
        <box size="${wheelbase} ${width} ${height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

   ### imu
  <joint name="base_to_imu" type="fixed">
    <parent link="base_link"/>
    <child link="imu_sensor"/>
    <origin xyz="${imu_distance_from_base_link} 0 ${ground_offset+height+(imu_height/2)}"/>
  </joint>

  <link name="imu_sensor">
    <visual>
      <geometry>
        <cylinder radius="${imu_radius}" length="${imu_height}"/>
        <!--mesh filename="package://agbot_0/meshes/sorting_tray_centered.stl" scale="0.001 0.001 0.001"-->
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  ### gps
  <joint name="base_to_gps" type="fixed">
    <parent link="base_link"/>
    <child link="gps_sensor"/>
    <origin xyz="${gps_distance_from_base_link} 0 ${ground_offset+height+(gps_height/2)}"/>
  </joint>

  <link name="gps_sensor">
    <visual>
      <geometry>
        <cylinder radius="${gps_radius}" length="${gps_height}"/>
        <!--mesh filename="package://agbot_0/meshes/sorting_tray_centered.stl" scale="0.001 0.001 0.001"-->
      </geometry>
      <material name="red"/>
    </visual>
  </link>

  ### laser
  <joint name="base_to_laser_model" type="fixed">
    <parent link="base_link"/>
    <child link="laser_model"/>
    <origin xyz="${laser_distance_from_base_link} 0 ${ground_offset+height+(gps_height/2)}"/>
  </joint>

  <link name="laser_model">
    <visual>
      <geometry>
        <cylinder radius="${laser_radius}" length="${gps_height}"/>
        <!--mesh filename="package://agbot_0/meshes/sorting_tray_centered.stl" scale="0.001 0.001 0.001"-->
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  ### Back left wheel
  <joint name="base_to_back_left_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="back_left_wheel"/>
    <origin xyz="0 ${(wheel_length+width)/2+wheel_offset} ${wheel_radius}"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="back_left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
  </link>

  ### Back right wheel
  <joint name="base_to_back_right_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="back_right_wheel"/>
    <origin xyz="0 ${-(wheel_length+width)/2-wheel_offset} ${wheel_radius}"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="back_right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
  </link>

  ### Front right wheel
  <joint name="base_to_front_left_hinge" type="continuous">
    <parent link="base_link"/>
    <child link="front_left_hinge"/>
    <origin xyz="${wheelbase} ${(wheel_length+width)/2+wheel_offset} ${wheel_radius}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="front_left_hinge"/>

  <joint name="front_left_hinge_to_wheel" type="continuous">
    <parent link="front_left_hinge"/>
    <child link="front_left_wheel"/>
    <axis xyz="0 1 0"/>
    <orign xyz="0 ${wheel_length/2} 0"/>
  </joint>

  <link name="front_left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
  </link>

  ### Front left wheel
  <joint name="base_to_front_right_hinge" type="continuous">
    <parent link="base_link"/>
    <child link="front_right_hinge"/>
    <origin xyz="${wheelbase} ${-(width)/2-wheel_offset} ${wheel_radius}"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="front_right_hinge"/>

  <joint name="front_right_hinge_to_wheel" type="continuous">
    <parent link="front_right_hinge"/>
    <child link="front_right_wheel"/>
    <axis xyz="0 1 0"/>
    <origin xyz="0 ${-(wheel_length)/2} 0"/>
  </joint>

  <link name="front_right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="black"/>
      <origin rpy="${pi/2} 0 0"  />
    </visual>
  </link>

  <gazebo>
    <plugin name="imu_plugin" filename="libgazebo_ros_imu.so">
      <alwaysOn>true</alwaysOn>
      <bodyName>imu_sensor</bodyName>
      <topicName>/imu/data</topicName>
      <serviceName>imu_service</serviceName>
      <gaussianNoise>0.0</gaussianNoise>
      <updateRate>20.0</updateRate>
    </plugin>

    <plugin name="gazebo_ros_gps" filename="libhector_gazebo_ros_gps.so">
        <updateRate>4.0</updateRate>
        <bodyName>gps_sensor</bodyName>
        <frameId>gps_sensor</frameId>
        <topicName>/gps/fix</topicName>
        <velocityTopicName>/gps/fix_velocity</velocityTopicName>
        <referenceLatitude>39.78020</referenceLatitude>
        <referenceLongitude>-86.16289</referenceLongitude>
        <referenceHeading>90</referenceHeading>
        <referenceAltitude>10</referenceAltitude>
        <offset>0 0 0</offset>
        <drift>0.001 0.001 0.001</drift>
        <gaussianNoise>5.0 5.0 5.0</gaussianNoise>
        <velocityDrift>0.001 0.001 0.001</velocityDrift>
        <velocityGaussianNoise>0.5 0.5 0.5</velocityGaussianNoise>
<!--                <drift>0.001 0.001 0.001</drift>-->
<!--                <gaussianNoise>0.01 0.01 0.01</gaussianNoise>-->
<!--                <velocityDrift>0 0 0</velocityDrift>-->
<!--                <velocityGaussianNoise>0.05 0.05 0.05</velocityGaussianNoise>-->
    </plugin>
  </gazebo>

</robot>
