teleop:
  roboclaw_3:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: roboclaw/cmd_vel 
    deadman_buttons: [1] # X button
    axis_mappings:
      -
        axis: 4 # right shoulder trigger to control wheel speed
        target: linear.x
        scale: -0.05
        offset: 0.05
